coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
